# Generated by Django 5.2.11 on 2026-02-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(True, 'Новостройка'), (False, 'Вторичка'), (None, 'Неизвестно')], default=None, null=True, verbose_name='New building'),
        ),
    ]
