# Generated by Django 5.2.11 on 2026-02-15 19:59

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.only('owners_phonenumber', 'owner_pure_phone')
    for flat in flats:
        try:
            parsed_owners_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            if phonenumbers.is_valid_number(parsed_owners_phonenumber):
                flat.owner_pure_phone = parsed_owners_phonenumber
                flat.save(update_fields=['owner_pure_phone'])
        except Exception:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone_alter_flat_liked_by'),
    ]

    operations = [migrations.RunPython(fill_owner_pure_phone_field)
    ]
