# Generated by Django 5.2.11 on 2026-02-22 12:40

from django.db import migrations


def transfer_owner_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.only(
                'owner',
                'owners_phonenumber',
                'owner_pure_phone'
             )
    for flat in flats:
        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_flat_owner_pure_phone_owner'),
    ]

    operations = [migrations.RunPython(transfer_owner_data)
    ]
