# Generated by Django 5.2.11 on 2026-02-22 21:49

from django.db import migrations


def connect_flats_with_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners:
        flats=Flat.objects.filter(
            owner=owner.name,
            owner_pure_phone=owner.pure_phone
            )
        owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_owner_name_alter_owner_phonenumber_and_more'),
    ]

    operations = [migrations.RunPython(connect_flats_with_owners)
    ]
