# Generated by Django 5.2.11 on 2026-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_flat_owner_remove_flat_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(True, 'Новостройка'), (False, 'Вторичка'), (None, 'Неизвестно')], db_index=True, default=None, null=True, verbose_name='New building'),
        ),
    ]
